//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.FlightResult = new HashSet<FlightResult>();
        }
    
        public int IdFlight { get; set; }
        public System.DateTime Date { get; set; }
        public string City { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.DateTime TimeStart { get; set; }
        public string FlightWeather { get; set; }
        public string ArrivalWeather { get; set; }
        public System.DateTime ClockSet { get; set; }
        public System.DateTime ClockEcho { get; set; }
        public int SeriePigeonsFromStartList { get; set; }
        public int SeriePigeonsFromClockList { get; set; }
        public string CatA { get; set; }
        public string CatB { get; set; }
        public string CatC { get; set; }
        public string CatM { get; set; }
        public Nullable<double> ConstantPoints { get; set; }
        public Nullable<int> FancierQuantity { get; set; }
        public Nullable<int> PigeonsQuantity { get; set; }
        public Nullable<int> ScorePoints { get; set; }
        public Nullable<System.TimeSpan> FirstPigeonTime { get; set; }
        public Nullable<double> FirstPigeonSpeed { get; set; }
        public Nullable<System.TimeSpan> LastPigeonTime { get; set; }
        public Nullable<double> LastPigeonSpeed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightResult> FlightResult { get; set; }
    }
}
