//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDove
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightResult
    {
        public int IdFlightResult { get; set; }
        public string IdPigeon { get; set; }
        public Nullable<int> IdFlight { get; set; }
        public System.TimeSpan TimeArrival { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<double> Coeficient { get; set; }
        public Nullable<double> GMP { get; set; }
        public Nullable<double> Points { get; set; }
        public Nullable<double> Distance { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Pigeon Pigeon { get; set; }
    }
}
