//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDove
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IDoveEntities : DbContext
    {
        public IDoveEntities()
            : base("name=IDoveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Dovecote> Dovecote { get; set; }
        public virtual DbSet<Fancier> Fancier { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<FlightResult> FlightResult { get; set; }
        public virtual DbSet<Pigeon> Pigeon { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Section> Section { get; set; }
    }
}
