//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pigeons
    {
        public string IdPigeon { get; set; }
        public string PigeonNumber { get; set; }
        public string IdDovecote { get; set; }
        public string Color { get; set; }
        public string Country { get; set; }
        public string Yearbook { get; set; }
    
        public virtual Dovecote Dovecote { get; set; }
    }
}
