//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDove
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pigeon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pigeon()
        {
            this.FlightResult = new HashSet<FlightResult>();
        }
    
        public string IdPigeon { get; set; }
        public string IdFancier { get; set; }
        public string Country { get; set; }
        public Nullable<int> IdColor { get; set; }
        public string Yearbook { get; set; }
        public int Sex { get; set; }
        public string Number { get; set; }
        public string IdBranch { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Fancier Fancier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightResult> FlightResult { get; set; }
    }
}
